# Generated by Django 5.2.5 on 2025-08-25 13:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('oidc', 'OIDC'), ('saml', 'SAML')], max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('allowed_email_domains', models.TextField(blank=True, default='')),
                ('oidc_issuer', models.URLField(blank=True, null=True)),
                ('oidc_client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('oidc_client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('oidc_scopes', models.CharField(blank=True, default='openid profile email', max_length=255, null=True)),
                ('saml_entity_id', models.CharField(blank=True, max_length=512, null=True)),
                ('saml_idp_sso_url', models.URLField(blank=True, null=True)),
                ('saml_idp_x509cert', models.TextField(blank=True, null=True)),
                ('saml_nameid_format', models.CharField(blank=True, default='urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress', max_length=255, null=True)),
                ('ldap_server_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('ldap_bind_dn', models.CharField(blank=True, max_length=255, null=True)),
                ('ldap_bind_password', models.CharField(blank=True, max_length=255, null=True)),
                ('ldap_user_search_base', models.CharField(blank=True, max_length=255, null=True)),
                ('ldap_user_filter', models.CharField(blank=True, default='(mail=%(user)s)', max_length=255, null=True)),
                ('ldap_start_tls', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sso_sso_config', to='accounts.organisation')),
            ],
        ),
    ]
